target_sources(Graphics
  PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.hpp
    ${CMAKE_CURRENT_LIST_DIR}/AppBuiltInTypes.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ByteBuffer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ByteBuffer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Camera.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Camera.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ComputePass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ComputePass.hpp
    ${CMAKE_CURRENT_LIST_DIR}/GraphicsStandard.hpp
    ${CMAKE_CURRENT_LIST_DIR}/GraphicsSpace.cpp
    ${CMAKE_CURRENT_LIST_DIR}/GraphicsSpace.hpp
    ${CMAKE_CURRENT_LIST_DIR}/MaterialProperties.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MaterialProperties.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Material.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Material.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Mesh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Mesh.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Texture.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Texture.hpp
    ${CMAKE_CURRENT_LIST_DIR}/MaterialUniformBufferHelper.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MaterialUniformBufferHelper.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Model.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Model.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Shader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Shader.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ShaderProperties.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ShaderProperties.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Buffers.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Buffers.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Renderer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Renderer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchShaderManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchShaderManager.hpp
)
