target_sources(Graphics
  PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.hpp
    ${CMAKE_CURRENT_LIST_DIR}/GraphicsStandard.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Material.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Material.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Mesh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Mesh.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Texture.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Texture.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Model.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Model.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ShaderProgram.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ShaderProgram.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Renderer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Renderer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ResourceLibrary.inl
    ${CMAKE_CURRENT_LIST_DIR}/ResourceLibrary.hpp
    ${CMAKE_CURRENT_LIST_DIR}/OpenGlRenderer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/OpenGlRenderer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/FrameworkZilchShaderGlslBackend.cpp
    ${CMAKE_CURRENT_LIST_DIR}/FrameworkZilchShaderGlslBackend.hpp
)
